name: dummy
send_to_s3: false
fetch_from_s3: false
explore:
  account:               # Name of ActiveRecord class in snake_case
    tactic: all       # Scrubbing tactic to use (see Brillo:TACTICS for choices)
obfuscations:         #
  accounts.name: name
  accounts.email: email
  accounts.phone: phone_with_id
