name: my-app          # Namespace the scrubbed file will occupy
## Optional configuration (with defaults shown)
# compress: true      # Enables gzip on scrub and ungzip on load
#
# obfuscations:
#   user.name: name   # Scrub table.field with scrubber (see Brillo::SCRUBBERS for choices)
transfer:
  # enabled: true     # Disable to skip transferring to and from S3, running purely locally
  # bucket: database-scrubs
  # region: us-west-2 # Override to change the region to somewhere nearer you
# explore:              # Legacy support for top leve explore
  # user:               # Name of ActiveRecord class in snake_case
  #   tactic: all       # Scrubbing tactic to use (see Brillo:TACTICS for choices)
  #   associations:     # Associations to include in the scrub (ALL associated records included)
  #     - comments

files:      # Write across multiple files.
  - filename: my_first_file # Filename to write seed to.
    # include_schema: true  # Support skipping schema load.
    # recreate_on_import: true # Recreate DB and reload schema when this file loads
    explore:     # Same functionality of explore above.
