# Example Config:
#
name: my-app          # Namespace the scrubbed file will occupy
# dry_run: true       # Enable to print scrubber output to console instead of uploading
explore:
  user:               # Name of ActiveRecord class in snake_case
    tactic: all       # Scrubbing tactic to use (see Brillo:TACTICS for choices)
    associations:     # Associations to include in the scrub (ALL associated records included)
      - comments
# obfuscations:         #
#   user.name: name     # Scrub table.field with scrubber (see Brillo::SCRUBBERS for choices)
