name: dummy
transfer_enabled: false
explore:
  account:            # Name of ActiveRecord class in snake_case
    tactic: all       # Scrubbing tactic to use (see Brillo:TACTICS for choices)
obfuscations:
  accounts.name: name
  accounts.email: email
  accounts.phone: phone_with_id
