defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  pool: 10

test:
  <<: *defaults
  database: brillo_test

development:
  <<: *defaults
  database: brillo_development
  socket: /tmp/mysql.sock
  host: localhost
